<?php
/**
 * South Atlantic Region custom fields
 *
 * @package uri-ticks
 */

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
	 array(
		 'key' => 'group_5e3db0674dce2',
		 'title' => 'South Atlantic Region',
		 'fields' => array(
			 array(
				 'key' => 'field_5e3db06754dbd',
				 'label' => 'Abundance',
				 'name' => 'south_atlantic_abundance',
				 'type' => 'number',
				 'instructions' => 'Assign a numerical abundance or leave blank if no presence. Do not use on life stage posts.',
				 'required' => 0,
				 'conditional_logic' => 0,
				 'wrapper' => array(
					 'width' => '',
					 'class' => '',
					 'id' => '',
				 ),
				 'default_value' => '',
				 'placeholder' => '',
				 'prepend' => '',
				 'append' => '',
				 'min' => '',
				 'max' => '',
				 'step' => '',
			 ),
			 array(
				 'key' => 'field_5e3db06754ddc',
				 'label' => 'Diseases',
				 'name' => 'south_atlantic_diseases',
				 'type' => 'taxonomy',
				 'instructions' => 'Assign diseases carried by this life stage. Do not use on species posts.',
				 'required' => 0,
				 'conditional_logic' => 0,
				 'wrapper' => array(
					 'width' => '',
					 'class' => '',
					 'id' => '',
				 ),
				 'taxonomy' => 'disease',
				 'field_type' => 'checkbox',
				 'add_term' => 1,
				 'save_terms' => 0,
				 'load_terms' => 0,
				 'return_format' => 'id',
				 'multiple' => 0,
				 'allow_null' => 0,
			 ),
			 array(
				 'key' => 'field_5e3db06754de6',
				 'label' => 'Activity',
				 'name' => 'south_atlantic_activity',
				 'type' => 'group',
				 'instructions' => 'Assign a numerical activity level for each month or leave blank if no activity. Do not use on species posts.',
				 'required' => 0,
				 'conditional_logic' => 0,
				 'wrapper' => array(
					 'width' => '',
					 'class' => '',
					 'id' => '',
				 ),
				 'layout' => 'table',
				 'sub_fields' => array(
					 array(
						 'key' => 'field_5e3db06759956',
						 'label' => 'January',
						 'name' => 'january',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db06759960',
						 'label' => 'February',
						 'name' => 'february',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db06759965',
						 'label' => 'March',
						 'name' => 'march',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db0675996a',
						 'label' => 'April',
						 'name' => 'april',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db06759970',
						 'label' => 'May',
						 'name' => 'may',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db06759975',
						 'label' => 'June',
						 'name' => 'june',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db0675997a',
						 'label' => 'July',
						 'name' => 'july',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db0675997e',
						 'label' => 'August',
						 'name' => 'august',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db06759983',
						 'label' => 'September',
						 'name' => 'september',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db06759988',
						 'label' => 'October',
						 'name' => 'october',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db0675998d',
						 'label' => 'November',
						 'name' => 'november',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
					 array(
						 'key' => 'field_5e3db06759992',
						 'label' => 'December',
						 'name' => 'december',
						 'type' => 'number',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'min' => '',
						 'max' => '',
						 'step' => '',
					 ),
				 ),
			 ),
		 ),
		 'location' => array(
			 array(
				 array(
					 'param' => 'post_type',
					 'operator' => '==',
					 'value' => 'tick',
				 ),
			 ),
		 ),
		 'menu_order' => 0,
		 'position' => 'normal',
		 'style' => 'default',
		 'label_placement' => 'left',
		 'instruction_placement' => 'label',
		 'hide_on_screen' => '',
		 'active' => true,
		 'description' => '',
	 )
	 );

 endif;
